#!/bin/bash
# path variables
pathucidefaults="files/etc/uci-defaults"
pathuciconfig="files/etc/config"
pathucidropbear="files/etc/dropbear"
pathcp="/bin/cp"
pathopenwrtbin="bin"
pathopenvpncerts="/etc/openvpn"

# non private
pathmodules="ffcp_modules.d"
pathdevices="ffcp_devices.d"
pathparameters="ffcp_parameters.d"
pathenv="ffcp_env.d"
pathhwconfig="ffcp_config.d"
pathbinout="ffcp_bins"
# private
pathmodulespriv="ffcp_private_modules.d"
pathdevicespriv="ffcp_private_devices.d"
pathparameterspriv="ffcp_private_parameters.d"
pathenvpriv="ffcp_private_env.d"
pathhwconfigpriv="ffcp_private_config.d"
pathbinoutpriv="ffcp_private_bins"

# file variables
filesshpubkeys="sshpubkeys"
fileuciparameter="ffcp_parameter.conf"
fileucienv="ffcp_env.conf"
filemodulealfred="$pathuciconfig/alfred"
filemodulebatmanadv="$pathuciconfig/batman-adv"
filemoduleddns="$pathuciconfig/ddns"
filemoduledhcp="$pathuciconfig/dhcp"
filemoduledropear="$pathuciconfig/dropbear"
filemodulefirewall="$pathuciconfig/firewall"
filemodulenetwork="$pathuciconfig/network"
filemoduleopenvpn="$pathuciconfig/openvpn"
filemodulesystem="$pathuciconfig/system"
filemodulevnstat="$pathuciconfig/vnstat"
filemodulewireless="$pathuciconfig/wireless"

filehwconfig=".config"
filehwconfigbefore=".config.before"
filedropbearkeys="authorized_keys"

# bin file lists
filebinc7v2="openwrt-ar71xx-generic-archer-c7-v2-squashfs-factory.bin openwrt-ar71xx-generic-archer-c7-v2-squashfs-sysupgrade.bin"
filebin4300v1="openwrt-ar71xx-generic-tl-wdr4300-v1-il-squashfs-factory.bin openwrt-ar71xx-generic-tl-wdr4300-v1-squashfs-factory.bin openwrt-ar71xx-generic-tl-wdr4300-v1-il-squashfs-sysupgrade.bin openwrt-ar71xx-generic-tl-wdr4300-v1-squashfs-sysupgrade.bin"
filebin1043v1="openwrt-ar71xx-generic-tl-wr1043nd-v1-squashfs-factory.bin openwrt-ar71xx-generic-tl-wr1043nd-v1-squashfs-sysupgrade.bin"
filebinwndr3700v1="openwrt-ar71xx-generic-wndr3700-squashfs-factory.img openwrt-ar71xx-generic-wndr3700-squashfs-factory-NA.img openwrt-ar71xx-generic-wndr3700-squashfs-sysupgrade.bin"
filebinx86kvm="openwrt-x86-kvm_guest-combined-ext4.img"

modulegroups=(alfred batmanadv ddns dhcp dropbear firewall network openvpn system vnstat wireless)
recreateconfig="true"
buildthreads=5
