#!/bin/ash
tq=$(sudo batctl o | egrep "^c4:6e:1f:ea:c0:d6"|awk -F'(' '{print $2}'|awk -F')' '{print $1}')
echo $(expr $tq % 2.55)
loss=$(sudo batctl p -c 3 $1 | grep loss|awk -F, '{print $3}'|awk -F'\%' '{print $1}')
echo `expr 100 - $loss`
