#!/bin/ash
# env variables
source ffcp_parameter.conf
# not yet, but in the future try to read from ffcp_parameter.conf and insert into EOF script

if [ ! -f /etc/config/gluon-node-info ]; then
	cat <<EOF >> /etc/config/gluon-node-info
	config location
	        option share_location '1'
	        option latitude '50.857165'
	        option longitude '6.154833'

	config owner
	        option contact 'billgates@microsoft.com'
	EOF
fi
exit 0
