#!/bin/ash
# env variables
source ffcp_parameter.conf

randomized=$(</dev/urandom tr -dc A-Z-a-z-0-9 | head -c24)
sourceeth="eth0"
privulafirst8="FD"
guestnetidentifier=1
privnetidentifier=2

#get last 40 bits from $sourceeth interface (spine)
hwaddr=$(ifconfig $sourceeth|grep HWaddr|awk '{print $5}')
hwaddrwocolon=$(echo $hwaddr|sed -e 's/://g')

guestnet=`echo $privulafirst8${hwaddrwocolon:2:2}:${hwaddrwocolon:4:2}${hwaddrwocolon:6:2}:${hwaddrwocolon:8:2}${hwaddrwocolon:10:1}$guestnetidentifier::/64`
guestnetip=`echo $privulafirst8${hwaddrwocolon:2:2}:${hwaddrwocolon:4:2}${hwaddrwocolon:6:2}:${hwaddrwocolon:8:2}${hwaddrwocolon:10:1}$guestnetidentifier::1/64`

privnet="$privulafirst8${hwaddrwocolon:2:2}:${hwaddrwocolon:4:2}${hwaddrwocolon:6:2}:${hwaddrwocolon:8:2}${hwaddrwocolon:10:1}$privnetidentifier::/64"
privnetip=`echo $privulafirst8${hwaddrwocolon:2:2}:${hwaddrwocolon:4:2}${hwaddrwocolon:6:2}:${hwaddrwocolon:8:2}${hwaddrwocolon:10:1}$privnetidentifier::1/64)`

# UCI
# hostname
uci set system.@system[0].hostname=$(echo -n "$hostnamebasis$hwaddrwocolon")
# private net ula
uci set network.lan.ula_prefix=$privnet
# mesh net ula
uci set network.guests.ula_prefix="$domainula/$domainulasize"

# set release/version
grep Version /etc/banner | awk '{ print $2}' > /lib/gluon/gluon-version
grep Release /etc/banner | awk '{ print $2}' > /lib/gluon/release

# set default MAC for gluon
echo $hwaddr > /lib/gluon/core/sysconfig/primary_mac

# repair init script announced
# old
#sed -i 's/collect.lua/announce.lua/g' /etc/hotplug.d/iface/10-gluon-announced
#chmod +x /lib/gluon/announce/collect.lua

uci set wireless.radio1.channel='$channel24'
uci set wireless.radio0.channel='$channel5'

uci commit
exit 0
